[package]
name = "wq"
version = "0.3.1"
edition = "2024"
build = "build.rs"

[dependencies]
colored = "3.0.0"
rand = "0.9.2"
once_cell = "1.21.3"
rustyline = "16.0.0"
textplots = "0.8.7"
rgb = "0.8.52"